palavra = input("Digite uma palavra: ")
print ('O tipo primitivo desse valor é ', type(palavra))
print(f'Só tem espaços? {palavra.isspace()}')
print(f'É um numero? {palavra.isnumeric()}')
print(f'É alfabetico? {palavra.isalpha()}')
print(f'É alfanumerico? {palavra.isalnum()}')
print(f'É maiúsculas? {palavra.isupper()}')
print(f'É minúsculas? {palavra.islower()}')
print(f'É capitalizada? {palavra.istitle()}')